apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 5

    successCondition: result[0] >= 0.99
    failureLimit: 2

    provider:
      prometheus:
        address: http://prometheus.monitoring.svc:9090
        query: |
          sum(rate(http_requests_total{app="myapp",status!~"5.."}[5m]))
          /
          sum(rate(http_requests_total{app="myapp"}[5m]))
          