apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-test
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-test
  template:
    metadata:
      labels:
        app: grpc-test
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command:
            - sleep
            - "3600"