apiVersion: v1
kind: Namespace
metadata:
  name: online-boutique
  labels:
    # pod-security.kubernetes.io/enforce: restricted
    istio.io/rev: default
---
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: dev-limitrange
#   namespace: production
# spec:
#   limits:
#   - type: Container
#     default:
#       cpu: "300m"
#       memory: "256Mi"
#     max:
#       cpu: "1"
#       memory: "512Mi"
# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: quota
#   namespace: production
# spec:
#   hard:
#     pods: "30"
#     requests.cpu: "6"
#     requests.memory: "10Gi"