apiVersion: v1
kind: Secret
metadata:
  name: cd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: https://github.com/xin1lanthua123/CD-repo.git
  username: xin1lanthua123
  password: ghp_xxxxxxxxxxxxxxxxxxxxxxxxx
