apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque

stringData:
  githubAppID: "4353582"
  githubAppInstallationID: "147978071"
  type: git
  url: https://github.com/xin1lanthua123/CD-repo.git
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAp6ohTtzRFCwi25YYsmRqQcO8xumA3O8a1Aj7JwZT+3ox5CSK
    jjzTzEE3l96rl8xyQBWhIKBUIevCUaIfyzkg3q21S2TNhXGgDlUwFj3Mlb50oJQv
    pvCnMJkIB/IC7G1Fd2zmk9EO9JP3VJiSc0m7Ou0+y1sKrjkDp/ffIFq6M0KkiBlj
    wj2yRdWdhj9SGCKt6EpR9z9i4jya+puKJ2lZRBDAWrqG2a5s0X8o8EXFcCbO9t9j
    8B1JHbYlnaeHVLheB1yHQ0hfVMpWjGc640MfNSs+uEnVGG0jYCXjBxzWhlsGJzBl
    9H716YdPydoIA1TTiS3ZN9/yzs1woH9gpF45PQIDAQABAoIBABpqJkc7aMEp1vAL
    bKamRUtJIDOiVAf6r5paM99JEvAap0OPMjkIgkG6wJxvm08WCaXpAnKWb8rMTtf3
    l9S3kmMisN5I6kwsw4+egi3u3I127P7jecJuRZjVczt1OFqxOHGBOa5uEFIeAahV
    RTVel13IRM1a8YrTNq0+0utQ/+bVRqtfXnvW8ngEbigl//yGpiEeW5axRzcu+w3w
    JE8veORKPYLzOksCnAZs50dtPi6Idz356IisIKHAnF0uBlCJ1fLmjHCGsc9ual+K
    nj08tg36yeMUdBABwb58Xdp6P9QK+/28lUqep6ms+Au/GSFn1CkTNHyypUzM4YoS
    XZg2rK0CgYEA16/VB42DGmjtmpbZAKDdyJ1qVVae2biLioydD4WX5se+lqaYHTwu
    CJb1tcbfmu4WRVvFBwxfafPB/p/CWXBZMWGSgIvlmhD1PL9llu9H1lSlNC84o3y3
    ZsRbNMIu+VIayl6p5srMlCa1HTHxpdXiXQxpgwwWCiLAiSuZlG8q5SMCgYEAxwCI
    JquOhrsjnMTMo/fJVHmy98Q8HyGnShQC1jBdiE93CWq5rQZVcnWsPlEuSiaoO+PS
    EzyJvy6u8ueFb8f0Mz/ZEWBBdrBmjGA1sFqOblLtiRA8lIA3tsz7C7jwSUythoUY
    gk6EexetCb1X6StdjBw77gmxgu4yYm/d5Yh6Ph8CgYA2y9spYhBuwz2qSqyy9iui
    biu3ppwQ4EvDVVoJuX0QCqsnBwgaVVG0qPWfyvjAGcDauifiVIhhGKauk9QCeQKQ
    AyP/OIuKishjOJUMtZngn/ygt2aCUosdtsEdNEBO40cfJtGvatJyySq2Uhv8b8xk
    q2SbAJUQ2idkMgmApoWVVQKBgHwAO9aEziHsGGvGQZHmg+CMmNVExQXNDZXeVEot
    Bws6IP2QMDS9np7c7kBCi6qO3gO7mRp9fYPQzhjz5TTbDrKklVj7dq9DihLsnGfQ
    dbIPII5ovKb4Ij9ZCRGr4qZ6DiKlark/vdOJ1DwebNoROJBmw303MxJX5LNr64Ps
    f+eXAoGAQ09Rdj10Js7zedFwn72H6WOYFH5ARkoRHDgiX1UAEs6dm9+ZaQC4f+H3
    Bp61IppXgUtx9sh4Ep9XxozteJgEjBjscQxm0a74Ow6qRwm0YShbSj1+4F1Vgfb0
    i/OnrRLrWyB6SgQDk9/WUYX6fikB0a9oqDENliRUUClChfRrWeg=
    -----END RSA PRIVATE KEY-----