# externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: staging
spec:
  refreshInterval: 5s # Check for updates every 5 seconds
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: elasticsearch-password # K8s Secret name
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: elasticsearch-password # AWS Secrets Manager secret name


