# externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack
  namespace: observability
spec:
  refreshInterval: 5s # Check for updates every 5 seconds
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-webhook # K8s Secret name
    creationPolicy: Owner
  data:
  - secretKey: slack-webhook-url
    remoteRef:
      key: prod/alertmanager # aws secret manager secret name
      property: slack-webhook-url


