apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name:  {{ .Values.checkoutService.name }}-vs

spec:
  hosts:
    -  {{ .Values.checkoutService.name }}

  http:
    - name: primary-route

      match:
        - headers:
            content-type:
              prefix: application/grpc

      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: unavailable,cancelled,resource-exhausted

      timeout: 5s

      route:

        - destination:
            host:  {{ .Values.checkoutService.name }}
            subset: stable
          weight: 100

        - destination:
            host:  {{ .Values.checkoutService.name }}
            subset: canary
          weight: 0