global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      targets: ["node_exporter:8000"]

rule_files:
  - alert_rules.yaml


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
--- 
# alert_rules.yaml
group:
  - name: node_alerts
    rules: 
      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode="user"}[1m])) * 100 < 80
        for: 10s
        labels: 
          severity: warning 
        annotations:
          summary: "High CPU Usage Detected"
          description: "CPU Usage < 80% for more than 60 seconds"
---
# alertmanager.yaml
config:
  global:
    resolve_timeout: 3m

route:
  receiver: "slack-notification"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  routes:
    - receivers: "slack-notification"
      matcher: 
        - severity = "critical" 

receivers:
  - name: "slack-notification"
    slack_configs: 
      - send_resolved: true
        channel: "#devops-alert-monitoring"
        username: "Prometheus-Alert-Bot"
        icon_emoji: ":rotating_light"
        api_url: ""
---


