apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/xin1lanthua123/CD-repo.git
        revision: main
        files:
          - path: addons/*/addons.yaml

  template:
    metadata:
      name: '{{name}}-app'

    spec:
      project: default

      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
            - addons/{{name}}/values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PruneLast=true