apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=err
  generators:
    - git:
        repoURL: https://github.com/xin1lanthua123/CD-repo.git
        revision: main
        files:
          - path: addons/*/addons.yaml

  template:
    metadata:
      name: '{{.name}}-app'

    spec:
      project: default

      sources:
      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        releaseName: '{{.name}}'
        helm:
          valueFiles:
            - '$values/{{.valuesFile}}'

      - repoURL: https://github.com/xin1lanthua123/CD-repo.git
        targetRevision: main
        ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PruneLast=true