apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-helm
  namespace: argocd
spec:
  goTemplate: true
  # goTemplateOptions:
  #   - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/xin1lanthua123/CD-repo.git
        revision: main
        directories:
          - path: helm-chart/*
        
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        # ArgoCD Image Updater
        # Image alias
        argocd-image-updater.argoproj.io/image-list: >
          {{ .path.basename }}=quanldl/{{ .path.basename }}

        # Helm mapping
        argocd-image-updater.argoproj.io/{{ .path.basename }}.helm.image-name: image.repository

        argocd-image-updater.argoproj.io/{{ .path.basename }}.helm.image-tag: image.tag

        # Version Strategy
        argocd-image-updater.argoproj.io/{{ .path.basename }}.update-strategy: semver

        # Allow only SemVer
        argocd-image-updater.argoproj.io/{{ .path.basename }}.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$

        # Ignore latest
        argocd-image-updater.argoproj.io/{{ .path.basename }}.ignore-tags: latest

        # Force update
        argocd-image-updater.argoproj.io/{{ .path.basename }}.force-update: "true"

        # Docker Hub Pull Secret
        # argocd-image-updater.argoproj.io/{{ .path.basename }}.pull-secret: pullsecret:argocd/dockerhub-secret

        # Git Write Back
        argocd-image-updater.argoproj.io/write-back-method: git

        argocd-image-updater.argoproj.io/git-branch: main

        argocd-image-updater.argoproj.io/write-back-target: helmvalues

        argocd-image-updater.argoproj.io/git-repository: secret:argocd/github-app-credentials

        # Git Commit Identity
        argocd-image-updater.argoproj.io/git-commit-user-name: argocd-image-updater

        argocd-image-updater.argoproj.io/git-commit-user-email: bot@github.com
    spec:
      project: default

      source:
        repoURL: https://github.com/xin1lanthua123/CD-repo.git
        targetRevision: main
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: online-boutique

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true