apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: app-tg-config
  namespace: istio-system
spec:
  targetReference:
    name: istio-ingressgateway
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
        healthCheckProtocol: HTTP
        healthCheckPort: "15021"
        healthCheckPath: /healthz/ready

      