apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: app-tg-config
  namespace: online-boutique
spec:
  targetReference:
    name: frontend
  defaultConfiguration:
    targetType: ip
  
    healthCheckConfig:
      healthCheckProtocol: HTTP
      healthCheckPath: /_healthz
      