{{- if .Values.cartService.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.cartService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.cartService.name }}
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
{{- end }}