{{- if and .Values.frontend.create .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    {{- if eq .Values.frontend.workload.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else if eq .Values.frontend.workload.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ .Values.frontend.name }}

  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.targetCPU }}

    {{- if .Values.frontend.autoscaling.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.memory.target }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
      
        - type: Pods
          value: 4
          periodSeconds: 60

   
        - type: Percent
          value: 100
          periodSeconds: 60

    scaleDown:
    
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
       
        - type: Pods
          value: 1
          periodSeconds: 60
{{- end }}