apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.frontend.name }}-vs
  namespace: {{ .Release.Namespace }}

spec:
  hosts:
    {{- toYaml .Values.frontend.virtualService.hosts | nindent 4 }}

  gateways:
    - {{ .Values.frontend.virtualService.gateway.namespace }}/{{ .Values.frontend.virtualService.gateway.name }}

  http:
    - name: primary-route

      timeout: 5s

      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: gateway-error,connect-failure,refused-stream,unavailable,reset

      route:
        - destination:
            host: {{ .Values.frontend.name }}
            subset: stable
          weight: 100

        - destination:
            host: {{ .Values.frontend.name }}
            subset: canary
          weight: 0

