
{{- if .Values.frontend.create }}
{{- if .Values.frontend.virtualService.create }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.frontend.virtualService.hosts }}
  hosts:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  gateways:
  - {{ .Values.frontend.virtualService.gateway.namespace }}/{{ .Values.frontend.virtualService.gateway.name }}
  http:
  - name: primary-route

      timeout: 5s

      retries:
        attempts: 3
        perTryTimeout: 2s

        retryOn: >
          gateway-error,
          connect-failure,
          refused-stream,
          unavailable,
          reset
  - route:
    - destination:
        host: {{ .Values.frontend.name }}
        port:
          number: 80
{{- end }}
{{- end }}