name: prometheus-kube-stack

repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
version: 87.2.1

namespace: observability

valuesFile: addons/prometheus-kube-stack/prometheus-kube-stack-values.yaml