# name: validate workflow
# on:
#    pull_request:
#     branches:
#       - main
#    push:
#     branches:
#         - ci/feature/*
# jobs:
#   validate:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Run YAML Lint
#         uses: ibiqlik/action-yamllint@v3
#         with:
#           file_or_dir: .

#   helm-check:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Helm
#         uses: azure/setup-helm@v4

#       - name: Helm lint
#         working-directory: helm
#         run: |
#             find . -name "Chart.yaml" | while read -r file ; do
#                 dir=$(dirname "$file")
#                 helm lint $dir
#             done

#       - name: Helm template render check
#         working-directory: helm
#         run: |
#             find . -name "Chart.yaml"  | while read -r file ; do
#                 dir=$(dirname "$file")
#                 helm template test $dir > /dev/null
#             done

#   iac-scan:
#     name: " IaC Security Scan"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Run Checkov on Terraform
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           directory: infra/
#           framework: terraform
#           soft_fail: false
#           skip_check: CKV_AWS_39,CKV_AWS_58  # Public EKS endpoint (intentional for dev)
#           output_format: cli

#       - name: Run Checkov on Kubernetes manifests
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           directory: k8s/
#           framework: kubernetes
#           soft_fail: true  # Soft fail for K8s (some checks may not apply)
#           output_format: cli

